# Generated by Django 3.0.5 on 2020-05-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hamburguesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.URLField(max_length=300)),
                ('ingredientes', models.ManyToManyField(blank=True, related_name='hamburguesas', to='api.Ingrediente')),
            ],
        ),
    ]
